[package]
name = "pipeworkmc-server"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused_parens = "allow"
# TODO: missing_docs = "deny"


# ECS

[dependencies.bevy_ecs]
version  = "0.16"
features = [ "multi_threaded" ]

[dependencies.bevy_app]
version = "0.16"

# Serialisation

[dependencies.serde]
version  = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"

# Values

[dependencies.uuid]
version  = "1.18"
features = [ "serde" ]
